# This is a Docker Compose file for setting up the morphic-stack environment.

name: morphic-stack
services:
  morphic:
    container_name: morphic
    image: ghcr.io/miurla/morphic:latest
    env_file: .env.local # Load environment variables
    ports:
      - '3000:3000' # Maps port 3000 on the host to port 3000 in the container.
    # Supports for api urls with self-signed certificates
    #
    # volumes:
    #   - ./ca.pem:/certs/ca.crt
    # environment:
    #   - NODE_EXTRA_CA_CERTS=/certs/ca.crt
    depends_on:
      - redis
      - searxng

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    command: redis-server --appendonly yes

  searxng:
    image: searxng/searxng
    ports:
      - '${SEARXNG_PORT:-8080}:8080'
    env_file: .env.local # can remove if you want to use env variables or in settings.yml
    volumes:
      - ./searxng-limiter.toml:/etc/searxng/limiter.toml
      - ./searxng-settings.yml:/etc/searxng/settings.yml

volumes:
  redis:
